### PR TITLE
Updating the getting started page

### PR DESCRIPTION
**Pull request by bergerhoffer**

### CODE REVIEW

**Comment by bergerhoffer** [comment]
@johnsteele @d-s updates to the plugin's getting started page for your review.

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by johnsteele** [comment]
@bergerhoffer should the screenshots of Issue Explorer be updated to include the Windup server? I suppose it's not really a big deal since it's pretty self explanatory.

**Comment by bergerhoffer** [comment]
@johnsteele Sorry about the delay, I missed your question since I filter most of the Windup GitHub notifications. I've updated the PR with new screenshots.

**Pull request merged**
