### PR TITLE
WINDUP-1840 - Limit dependencies bundled in lib folder to only what i…

### PR DESCRIPTION
**Pull request by robstryker**
…s needed

Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by windupgithubbot1** [comment]
Can one of the admins verify this patch?

**Comment by robstryker** [comment]
A prelimenary test of this indicates no errors, but it's no exhaustive. A simple run of windup against a web app will complete the  ExecutionResults results = execBuilder.execute();   call without error, and will correcttly pass those results around in teh windup tools as expected. 

This patch decreases the size of the distributed plugin by 15%. The plugin currently bundles 130+ jars, of which only 22 are on the manifest.mf / classpath. 100+ jars sit uselessly and take up space. Of the 22 that *are* on the manifest, only 12 are actually needed (as far as I can tell.) 

Please see the JIRA for more information.

**Comment by robstryker** [comment]
Woohoo! My name's in the commit tree!  I'm a big guy now!

**Comment by johnsteele** [comment]
@robstryker Thanks for the contribution. I only found one small issue that stems from something ultimately needing to be reworked anyways.

**Pull request merged**
